add cloud-console only from admin-tools
openinfradev/decapod-base-yaml pull request #12
Opened 2021-01-04 07:15 UTC by intelliguy

클라우드 콘솔만 설치할 수 있는 workflow 작성
- cloudconsole + keycloak + postgresql

2021-01-04 07:31 UTC, Jaesang requested changes

2021-01-04 07:31 UTC, Jaesang commented on cloud-console/base/site-values.yaml
> +    config.keycloak.realm: nextpaas
nextpaas 말고 일반적인 realm 명으로 바꾸는게 좋아보입니다.

2021-01-04 07:32 UTC, intelliguy commented on cloud-console/base/site-values.yaml
> +    config.keycloak.realm: nextpaas
좋은 지적이십니다..
이 부분땜에 지난번 삽질을 했었으나... 대략 해결..

2021-01-04 08:31 UTC, jabbukka requested changes

2021-01-04 08:31 UTC, jabbukka commented on cloud-console/base/resources.yaml
> +          - keycloak.example.com
최근 kustomize 코드의 변경으로 override할 때 원래 값에 새로운 값이 append됩니다. 따라서 아래와 같이 변경되어야 할 것 같습니다.
```yaml
hosts: [] # TO_BE_FIXED
```

2021-01-04 08:31 UTC, jabbukka commented on cloud-console/base/resources.yaml
> +          - hosts:
이 곳도 변경이 필요합니다.
```yaml
- hosts: [] # TO_BE_FIXED
```

2021-01-06 05:57 UTC, intelliguy commented on cloud-console/base/resources.yaml
> +          - keycloak.example.com
사실 이 부분이 필요없어서 지우는게 낫겠네요

2021-01-06 08:21 UTC, jabbukka approved these changes

2021-01-06 08:28 UTC, Jaesang approved these changes

2021-01-07 02:13 UTC, merged