update Docs
openinfradev/decapod-base-yaml pull request #18
Opened 2021-01-14 09:34 UTC by jabbukka

2021-01-14 12:00 UTC, zugwan commented on README.md
> +It works with [decapod-site-yaml](https://github.com/openinfradev/decapod-site-yaml) which contain differences between each environment (_e.g. development, staging and production environment_).
contain -> contains 로 수정이 필요해 보입니다.

2021-01-14 12:26 UTC, zugwan requested changes

2021-01-14 12:26 UTC, zugwan commented on README.md
> +  * `base-yaml` is containig YAML resources and [overlays](https://kubectl.docs.kubernetes.io/references/kustomize/glossary/#overlay).
containig -> containing 로 수정이 필요해 보입니다.

2021-01-14 12:26 UTC, zugwan commented on README.md
> +* [Quick start](docs/quickstart.md)
doc/ 밑의 모든 문서가 링크 걸리는 것은 아닌거죠? 그 외 추가 정보는 doc/ 밑의 문서를 참고하라는 정도 표현을 추가해도 좋지 않을까 싶은데, 그냥 의견입니다. :smile:

2021-01-14 12:26 UTC, zugwan commented on docs/quickstart.md
> +$ .github/workflows/render.sh product_name # replace product_name to lma or openstack or cloud-console.
```suggestion
$ .github/workflows/render.sh <product name> # replace <product name> with lma or openstack or cloud-console.
```
변경해야 할 지점을 강조하는 것이 좋을 듯 합니다.

2021-01-14 12:26 UTC, zugwan commented on docs/README.md
> +OpenStack Structures:
뭔가 내용이 쓰다만 것 처럼 혹은 불필요한 내용처럼 보이는데, 확인 부탁 드립니다.

2021-01-15 00:43 UTC, jabbukka commented on docs/README.md
> +OpenStack Structures:
이 파일은 필요없는 파일로 삭제하도록 하겠습니다.

2021-01-15 00:44 UTC, jabbukka commented on README.md
> +* [Quick start](docs/quickstart.md)
모든 링크를 추가하려고 했습니다 ㅎㅎ docs/README.md가 없어서 document의 목차?를 이곳에라도 추가해야 하지 않을까 싶어서요.

2021-01-15 00:45 UTC, jabbukka commented on docs/quickstart.md
> +$ .github/workflows/render.sh product_name # replace product_name to lma or openstack or cloud-console.
반영하였습니다.

2021-01-15 01:17 UTC, zugwan approved these changes

2021-01-15 01:17 UTC, merged