prepare-etcd-secret: apply the label changes after v1.20
openinfradev/decapod-base-yaml pull request #236
Opened 2023-06-23 08:56 UTC by intelliguy

- ref: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#urgent-upgrade-notes
1.20에서 마스터를 지칭하는 라벨이 바뀌었네요. 
aws에서 eks 위주로 작업하는 현재는 발현되지 않지만 vm에  cluster 설치하면 발생하고 byoh 작업시에도 만나게 될 예정입니다.
이에 따라 수정해 놓는 것이며 **주의 사항으로 site별로 이 값을 다시 override**하고 있는데 이 내용도 과거버전의 라벨을 지칭하고 있습니다.
따라서 필요한 타이밍에는 수정이 필요

2023-06-23 09:02 UTC, bluejayA requested changes
연결된 이슈 (티켓)이 없습니다. 생성해서 붙여주시기 바랍니다.

2023-06-23 09:40 UTC, bluejayA approved these changes

2023-06-23 09:41 UTC, bluejayA approved these changes

2023-06-26 09:43 UTC, ktkfree approved these changes

2023-06-26 09:43 UTC, merged